export const strings = {
  appName: "Wahala House",
  tagline: "Run the country. Feel the trade-offs.",
  start: "Start",
  newGame: "New game",
  back: "Exit",
  mapLabel: "Map of Nigeria by state",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  play: "Play",
  pause: "Pause",
  speed: { slow: "Slow", normal: "Normal", fast: "Fast" },
  speedLabel: "Game speed",
  dateLine: (year: number, quarter: number, week: number) =>
    `Year ${year} · Q${quarter} · Week ${week}`,
  meters: {
    treasury: "Treasury",
    debt: "Debt",
    inflation: "Inflation",
    naira: "Naira",
    approval: "Approval",
    stability: "Stability",
    assembly: "Assembly",
  },
  metricLabel: "Map colours show",
  metrics: {
    mood: "Mood",
    security: "Security",
    economy: "Economy",
    power: "Power",
    health: "Health",
    education: "Education",
    infrastructure: "Infrastructure",
    welfare: "Welfare",
  },
  legendLow: "Low",
  legendHigh: "High",
  jumpToState: "Pick a state",
  noSelection: "Select a state on the map to see its details.",
  closePanel: "Close",
  population: "Population",
  governor: "Governor",
  traitsLabel: "Traits",
  traits: {
    oil: "Oil",
    agriculture: "Agriculture",
    commercial_hub: "Commercial hub",
    urban_dense: "Dense urban",
    border: "Border",
    conflict_zone: "Conflict-prone",
    riverine: "Riverine",
    flood_prone: "Flood-prone",
    mining: "Mining",
    port: "Port",
  },
  zones: {
    NC: "North Central",
    NE: "North East",
    NW: "North West",
    SE: "South East",
    SS: "South South",
    SW: "South West",
  },
  ended: "The game has ended.",
  budget: {
    title: (year: number, quarter: number) =>
      `Year ${year} · Q${quarter} budget`,
    description:
      "Decide how the quarter's money is shared out. Every share you raise is taken from another sector.",
    envelope: "Quarterly envelope",
    debtService: "Debt service (fixed)",
    programme: "To spend",
    tabSectors: "Sectors",
    tabSplit: "Split by state",
    perQuarter: "per quarter",
    coverage: "Covers",
    coverageOfNeed: (pct: number) => `${pct}% of need`,
    levels: {
      starved: "Starved",
      thin: "Thin",
      ok: "Adequate",
      full: "Well funded",
    },
    allocation: {
      need: "By need",
      population: "By population",
      loyalty: "By loyalty",
    },
    allocationHelp: {
      need: "Weaker states get more.",
      population: "Bigger states get more.",
      loyalty:
        "Loyal governors get more. It buys support but is unfair to everyone else.",
    },
    keep: "Keep last budget",
    confirm: "Confirm budget",
  },
  sectorHelp: {
    security: "Police, military and intelligence.",
    health: "Hospitals, clinics and vaccines.",
    education: "Schools and teachers.",
    infrastructure: "Roads, bridges and ports.",
    power: "Generation, grid and tariffs.",
    economy: "Industry support and jobs.",
    welfare: "Cash support and social programmes.",
  },
  policies: {
    open: "Policies",
    title: "Policy menu",
    description: "Every policy has a price, a delay and a catch.",
    back: "All policies",
    cost: "Cost",
    running: "Running cost",
    perWeek: "per week",
    delay: "Takes effect in",
    weeks: (n: number) => `${n} wk${n === 1 ? "" : "s"}`,
    free: "Free",
    assembly: "Needs Assembly vote",
    noVote: "No vote needed",
    active: "In effect",
    pending: (n: number) => `Lands in ${n} wk${n === 1 ? "" : "s"}`,
    cooldown: (n: number) => `Available in ${n} wk${n === 1 ? "" : "s"}`,
    advisors: "What your advisers say",
    vote: "Assembly vote",
    voteSupport: "Your support",
    voteNeeded: "Needed",
    voteChance: (pct: number) => `${pct}% chance to pass`,
    sweetener: "Constituency projects",
    sweetenerHelp:
      "Spend treasury money on projects in lawmakers' districts to win votes.",
    pickZone: "Which zone?",
    enact: "Enact policy",
    holdVote: "Put it to a vote",
    hiddenSide: "Side effects stay hidden until they land.",
    categories: {
      fiscal: "Fiscal",
      monetary: "Monetary",
      trade: "Trade",
      security: "Security",
      energy: "Energy",
      social: "Social",
      governance: "Governance",
    },
    failures: {
      unknown_policy: "That policy does not exist.",
      game_over: "The game has ended.",
      already_active: "Already in effect.",
      cooldown: "Not available yet.",
      insufficient_funds: "The treasury cannot cover this.",
      zone_required: "Pick a zone first.",
      vote_failed: "The Assembly voted it down.",
    },
    toastEnacted: (name: string) => `${name} is now law.`,
    toastDelayed: (name: string, n: number) =>
      `${name} is now law, but contractors say add ${n} weeks.`,
    toastVoteFailed:
      "The Assembly voted it down. Support fell and the sweeteners are gone.",
    toastMain: (name: string) =>
      `${name}: the intended effects have kicked in.`,
    toastSide: (name: string) => `${name}: a side effect has landed.`,
  },
  events: {
    respond: "Your decision",
    free: "Free",
    cost: (c: string) => `Cost ${c}`,
    cantAfford: "Not enough in the treasury",
    later: "Decide later",
    expiresIn: (n: number) => `Auto-ignored in ${n} wk${n === 1 ? "" : "s"}`,
    mustDecide: "This needs a decision before time can move on.",
    alert: (title: string) => `Needs a response: ${title}`,
    markerLabel: (title: string, where: string) =>
      `${title}${where ? ` in ${where}` : ""}`,
    advisersSay: "Advisers",
    ignoreTag: "Ignore",
  },
  news: {
    title: "News",
    ticker: "Latest headline",
    empty: "Nothing in the news yet.",
    tone: "Tone",
    dry: "Dry",
    wahala: "Full Naija Wahala",
    open: "Open news log",
    week: (tick: number) => `Week ${tick}`,
  },
  briefing: {
    tab: "Advisers",
    intro: "Your advisers weigh in. They will not agree.",
  },
  setup: {
    title: "New game",
    intro: "Choose how your presidency will run.",
    mode: "Mode",
    modes: { term: "Term", survival: "Survival" },
    modeHelp: {
      term: "An election at the end of each term. Win it to keep going.",
      survival: "No scheduled election. Stay in office as long as you can.",
    },
    termLength: "Term length",
    years: (n: number) => `${n} years`,
    termsAllowed: "Terms allowed",
    terms: { 1: "One", 2: "Two", unlimited: "Unlimited" },
    difficulty: "Difficulty",
    difficulties: { easy: "Easy", realistic: "Realistic", brutal: "Brutal" },
    difficultyHelp: {
      easy: "More money, slower decay, fewer crises.",
      realistic: "Balanced and unforgiving enough.",
      brutal: "Less money, faster decay, a harder Assembly.",
    },
    speed: "Game speed",
    tone: "News tone",
    seed: "Seed (optional)",
    seedHelp: "The same seed and the same choices give the same game.",
    seedPlaceholder: "Leave blank for a random game",
    start: "Start your term",
    back: "Back",
  },
  election: {
    title: "Election day",
    description: (term: number) =>
      `Term ${term} is over and the country goes to the polls.`,
    candidates: { player: "You (PPF)", uda: "UDA", third: "Other parties" },
    firstRound: "First round",
    runoff: "Runoff",
    nationalVote: "National vote",
    spread:
      "The winner needs at least 25% of the vote in two-thirds of the states and in the FCT.",
    statesMeeting: (who: string, n: number, need: number) =>
      `${who}, states at 25% or more: ${n} of ${need} needed`,
    fct: "FCT at 25% or more",
    yes: "Yes",
    no: "No",
    verdict: {
      won: "You won the election.",
      wonRunoff:
        "You missed the spread in the first round, but won the runoff.",
      lost: "You lost the election.",
      lostRunoff:
        "You missed the spread in the first round and lost the runoff.",
    },
    winnerLine: (name: string) => `Winner: ${name}`,
    continueTerm: (term: number) => `Begin term ${term}`,
    seeLegacy: "See your legacy",
    wonHint: "Your mandate gives you a short honeymoon.",
  },
  legacy: {
    title: "Your legacy",
    outcomes: {
      coup: "Removed in a coup",
      impeachment: "Impeached by the Assembly",
      collapse: "The government collapsed",
      voted_out: "Voted out of office",
      term_limit: "Completed your terms",
      ongoing: "Still in office",
    },
    outcomeBlurb: {
      coup: "Stability collapsed and the security forces stepped in.",
      impeachment:
        "With approval and Assembly support gone, lawmakers removed you.",
      collapse: "The treasury ran dry while the streets were angry.",
      voted_out: "The voters chose someone else.",
      term_limit: "You served as long as the rules allow.",
      ongoing: "",
    },
    score: "Score",
    time: (years: number) => `${years.toFixed(1)} years in office`,
    timeLabel: "Time in office",
    yearsValue: (years: number) => `${years.toFixed(1)} years`,
    elections: (w: number, l: number) => `Elections: ${w} won, ${l} lost`,
    avgApproval: "Average approval",
    avgStability: "Average stability",
    peakInflation: "Peak inflation",
    finalMeters: "At the end",
    changes: "How the country changed",
    traded: "What you traded away",
    tradedNone: "Nothing fell noticeably. That is rare.",
    best: "Best-off states",
    worst: "Worst-off states",
    tradeoff: "Your biggest trade-off",
    tradeoffBudget: (hi: string, hiPct: number, lo: string, loPct: number) =>
      `You put ${hiPct}% of the budget into ${hi} and only ${loPct}% into ${lo}.`,
    timeline: "Key moments",
    timelineEmpty: "Nothing notable happened.",
    week: (tick: number) => `Week ${tick}`,
    policyEnacted: (name: string) => `Enacted ${name}`,
    policyFailed: (name: string) => `The Assembly rejected ${name}`,
    eventResponded: (title: string) => `Responded to: ${title}`,
    eventIgnored: (title: string) => `Let pass: ${title}`,
    electionWon: "Won an election",
    electionLost: "Lost an election",
    ended: "Your time in office ended",
    share: "Share your result",
    download: "Download image",
    shareText: (score: number, outcome: string) =>
      `I ran Wahala House: ${outcome}, score ${score}.`,
    again: "Play again",
    toTitle: "Title screen",
    delta: (v: number) =>
      Math.abs(v) < 0.05 ? "0.0" : `${v > 0 ? "+" : ""}${v.toFixed(1)}`,
  },
  system: {
    menu: "Menu",
    resume: "Resume",
    saveGame: "Save game",
    loadGame: "Load game",
    continueGame: "Continue",
    exportSave: "Export save file",
    importSave: "Import save file",
    settings: "Settings",
    about: "About and credits",
    aboutShort: "About",
    quit: "Quit to title",
    back: "Back",
    close: "Close",
    slots: {
      auto: "Autosave",
      "slot-1": "Slot 1",
      "slot-2": "Slot 2",
      "slot-3": "Slot 3",
    },
    empty: "Empty",
    summary: (
      year: number,
      quarter: number,
      term: number,
      mode: string,
      difficulty: string,
      approval: number,
    ) =>
      `Year ${year}, Q${quarter} · term ${term} · ${mode} · ${difficulty} · approval ${approval}%`,
    savedAt: (when: string) => `Saved ${when}`,
    save: "Save",
    load: "Load",
    overwrite: "Overwrite",
    delete: "Delete",
    saved: (slot: string) => `Saved to ${slot}.`,
    loaded: "Game loaded.",
    exported: "Save file downloaded.",
    imported: "Save file imported.",
    deleted: "Save deleted.",
    errors: {
      not_json: "That file is not a save file.",
      wrong_format: "That file is not a Wahala House save.",
      too_new: "That save is from a newer version of the game.",
      invalid_state: "That save is damaged and cannot be loaded.",
      unknown: "Something went wrong with that save.",
    },
    settingsTitle: "Settings",
    autosave: "Autosave",
    autosaveHelp:
      "Saves at the start of each quarter and when you leave the tab.",
    reduceMotion: "Animations",
    reduceMotionOptions: {
      system: "Follow device",
      on: "Reduce",
      off: "Allow",
    },
    defaultTone: "Default news tone",
    defaultSpeed: "Default game speed",
    clearData: "Delete all saved data",
    clearConfirm: "Tap again to delete every save and setting",
    cleared: "All saved data deleted.",
    aboutTitle: "About Wahala House",
    aboutBody:
      "A satirical governance sandbox set in a Nigeria-scale country. Every decision costs something somewhere else.",
    aboutFiction:
      "All parties, agencies, officials and events are fictional. Any resemblance to real people or institutions is coincidence.",
    aboutMap:
      "Map of Nigeria based on a MapSVG map, licensed under Creative Commons Attribution 4.0 (CC BY 4.0), distributed as @svg-maps/nigeria.",
    aboutData: "State populations and areas are rough public estimates.",
    aboutVersion: (v: string) => `Version ${v}`,
    modeNames: { term: "Term", survival: "Survival" },
    difficultyNames: { easy: "Easy", realistic: "Realistic", brutal: "Brutal" },
  },
  advisors: {
    finance: "Finance",
    security: "Security",
    health: "Health",
    politics: "Politics",
  },
} as const;
