export const strings = {
  appName: 'Wahala House',
  tagline: 'Run the country. Feel the trade-offs.',
  start: 'Start',
  back: 'Exit',
  mapLabel: 'Map of Nigeria by state',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  play: 'Play',
  pause: 'Pause',
  speed: { slow: 'Slow', normal: 'Normal', fast: 'Fast' },
  speedLabel: 'Game speed',
  dateLine: (year: number, quarter: number, week: number) => `Year ${year} · Q${quarter} · Week ${week}`,
  meters: {
    treasury: 'Treasury',
    inflation: 'Inflation',
    naira: 'Naira',
    approval: 'Approval',
    stability: 'Stability',
    assembly: 'Assembly',
  },
  metricLabel: 'Map colours show',
  metrics: {
    mood: 'Mood',
    security: 'Security',
    economy: 'Economy',
    power: 'Power',
    health: 'Health',
    education: 'Education',
    infrastructure: 'Infrastructure',
    welfare: 'Welfare',
  },
  legendLow: 'Low',
  legendHigh: 'High',
  jumpToState: 'Pick a state',
  noSelection: 'Select a state on the map to see its details.',
  closePanel: 'Close',
  population: 'Population',
  governor: 'Governor',
  traitsLabel: 'Traits',
  traits: {
    oil: 'Oil', agriculture: 'Agriculture', commercial_hub: 'Commercial hub', urban_dense: 'Dense urban',
    border: 'Border', conflict_zone: 'Conflict-prone', riverine: 'Riverine', flood_prone: 'Flood-prone',
    mining: 'Mining', port: 'Port',
  },
  zones: { NC: 'North Central', NE: 'North East', NW: 'North West', SE: 'South East', SS: 'South South', SW: 'South West' },
  quarterTitle: 'New quarter',
  quarterBody: 'The budget window is open. Detailed budget controls arrive in the next phase; for now the current budget carries on.',
  quarterConfirm: 'Continue',
  ended: 'The game has ended.',
} as const;
