export const strings = {
  appName: 'Wahala House',
  tagline: 'Run the country. Feel the trade-offs.',
  start: 'Start',
  back: 'Exit',
  mapLabel: 'Map of Nigeria by state',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  play: 'Play',
  pause: 'Pause',
  speed: { slow: 'Slow', normal: 'Normal', fast: 'Fast' },
  speedLabel: 'Game speed',
  dateLine: (year: number, quarter: number, week: number) => `Year ${year} · Q${quarter} · Week ${week}`,
  meters: {
    treasury: 'Treasury',
    inflation: 'Inflation',
    naira: 'Naira',
    approval: 'Approval',
    stability: 'Stability',
    assembly: 'Assembly',
  },
  metricLabel: 'Map colours show',
  metrics: {
    mood: 'Mood',
    security: 'Security',
    economy: 'Economy',
    power: 'Power',
    health: 'Health',
    education: 'Education',
    infrastructure: 'Infrastructure',
    welfare: 'Welfare',
  },
  legendLow: 'Low',
  legendHigh: 'High',
  jumpToState: 'Pick a state',
  noSelection: 'Select a state on the map to see its details.',
  closePanel: 'Close',
  population: 'Population',
  governor: 'Governor',
  traitsLabel: 'Traits',
  traits: {
    oil: 'Oil', agriculture: 'Agriculture', commercial_hub: 'Commercial hub', urban_dense: 'Dense urban',
    border: 'Border', conflict_zone: 'Conflict-prone', riverine: 'Riverine', flood_prone: 'Flood-prone',
    mining: 'Mining', port: 'Port',
  },
  zones: { NC: 'North Central', NE: 'North East', NW: 'North West', SE: 'South East', SS: 'South South', SW: 'South West' },
  ended: 'The game has ended.',
  budget: {
    title: (year: number, quarter: number) => `Year ${year} · Q${quarter} budget`,
    description: 'Decide how the quarter\'s money is shared out. Every share you raise is taken from another sector.',
    envelope: 'Quarterly envelope',
    debtService: 'Debt service (fixed)',
    programme: 'To spend',
    tabSectors: 'Sectors',
    tabSplit: 'Split by state',
    perQuarter: 'per quarter',
    coverage: 'Covers',
    coverageOfNeed: (pct: number) => `${pct}% of need`,
    levels: { starved: 'Starved', thin: 'Thin', ok: 'Adequate', full: 'Well funded' },
    allocation: {
      need: 'By need',
      population: 'By population',
      loyalty: 'By loyalty',
    },
    allocationHelp: {
      need: 'Weaker states get more.',
      population: 'Bigger states get more.',
      loyalty: 'Loyal governors get more. It buys support but is unfair to everyone else.',
    },
    keep: 'Keep last budget',
    confirm: 'Confirm budget',
  },
  sectorHelp: {
    security: 'Police, military and intelligence.',
    health: 'Hospitals, clinics and vaccines.',
    education: 'Schools and teachers.',
    infrastructure: 'Roads, bridges and ports.',
    power: 'Generation, grid and tariffs.',
    economy: 'Industry support and jobs.',
    welfare: 'Cash support and social programmes.',
  },
  policies: {
    open: 'Policies',
    title: 'Policy menu',
    description: 'Every policy has a price, a delay and a catch.',
    back: 'All policies',
    cost: 'Cost',
    running: 'Running cost',
    perWeek: 'per week',
    delay: 'Takes effect in',
    weeks: (n: number) => `${n} wk${n === 1 ? '' : 's'}`,
    free: 'Free',
    assembly: 'Needs Assembly vote',
    noVote: 'No vote needed',
    active: 'In effect',
    pending: (n: number) => `Lands in ${n} wk${n === 1 ? '' : 's'}`,
    cooldown: (n: number) => `Available in ${n} wk${n === 1 ? '' : 's'}`,
    advisors: 'What your advisers say',
    vote: 'Assembly vote',
    voteSupport: 'Your support',
    voteNeeded: 'Needed',
    voteChance: (pct: number) => `${pct}% chance to pass`,
    sweetener: 'Constituency projects',
    sweetenerHelp: 'Spend treasury money on projects in lawmakers\' districts to win votes.',
    pickZone: 'Which zone?',
    enact: 'Enact policy',
    holdVote: 'Put it to a vote',
    hiddenSide: 'Side effects stay hidden until they land.',
    categories: {
      fiscal: 'Fiscal', monetary: 'Monetary', trade: 'Trade', security: 'Security',
      energy: 'Energy', social: 'Social', governance: 'Governance',
    },
    failures: {
      unknown_policy: 'That policy does not exist.',
      game_over: 'The game has ended.',
      already_active: 'Already in effect.',
      cooldown: 'Not available yet.',
      insufficient_funds: 'The treasury cannot cover this.',
      zone_required: 'Pick a zone first.',
      vote_failed: 'The Assembly voted it down.',
    },
    toastEnacted: (name: string) => `${name} is now law.`,
    toastDelayed: (name: string, n: number) => `${name} is now law, but contractors say add ${n} weeks.`,
    toastVoteFailed: 'The Assembly voted it down. Support fell and the sweeteners are gone.',
    toastMain: (name: string) => `${name}: the intended effects have kicked in.`,
    toastSide: (name: string) => `${name}: a side effect has landed.`,
  },
  advisors: { finance: 'Finance', security: 'Security', health: 'Health', politics: 'Politics' },
} as const;
